/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.vizualizer;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Graph</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.VizualizerPackage#getGraph()
 * @model
 * @generated
 */
public interface Graph extends Tile
{
} // Graph
