/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.vizualizer;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Page</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page#getTiles <em>Tiles</em>}</li>
 * </ul>
 *
 * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.VizualizerPackage#getPage()
 * @model
 * @generated
 */
public interface Page extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.VizualizerPackage#getPage_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Tiles</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Tile}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Tiles</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Tiles</em>' containment reference list.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.VizualizerPackage#getPage_Tiles()
   * @model containment="true"
   * @generated
   */
  EList<Tile> getTiles();

} // Page
