/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.vizualizer;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.VizualizerFactory
 * @model kind="package"
 * @generated
 */
public interface VizualizerPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "vizualizer";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/sdu/iotvizualizerlanguage/Vizualizer";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "vizualizer";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VizualizerPackage eINSTANCE = org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SystemImpl <em>System</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SystemImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSystem()
   * @generated
   */
  int SYSTEM = 0;

  /**
   * The feature id for the '<em><b>Pages</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__PAGES = 0;

  /**
   * The feature id for the '<em><b>Sources</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SOURCES = 1;

  /**
   * The feature id for the '<em><b>Schemas</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM__SCHEMAS = 2;

  /**
   * The number of structural features of the '<em>System</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PageImpl <em>Page</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PageImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getPage()
   * @generated
   */
  int PAGE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Tiles</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE__TILES = 1;

  /**
   * The number of structural features of the '<em>Page</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.TileImpl <em>Tile</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.TileImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getTile()
   * @generated
   */
  int TILE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TILE__NAME = 0;

  /**
   * The number of structural features of the '<em>Tile</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TILE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.LinkImpl <em>Link</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.LinkImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getLink()
   * @generated
   */
  int LINK = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__NAME = TILE__NAME;

  /**
   * The feature id for the '<em><b>Page</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK__PAGE = TILE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Link</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LINK_FEATURE_COUNT = TILE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GraphImpl <em>Graph</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GraphImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getGraph()
   * @generated
   */
  int GRAPH = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH__NAME = TILE__NAME;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH__SOURCE = TILE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Graph</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GRAPH_FEATURE_COUNT = TILE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SourceImpl <em>Source</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SourceImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSource()
   * @generated
   */
  int SOURCE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE__NAME = 0;

  /**
   * The number of structural features of the '<em>Source</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOURCE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DatasourceImpl <em>Datasource</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DatasourceImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getDatasource()
   * @generated
   */
  int DATASOURCE = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASOURCE__NAME = SOURCE__NAME;

  /**
   * The feature id for the '<em><b>Source</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASOURCE__SOURCE = SOURCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Dimensions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASOURCE__DIMENSIONS = SOURCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Datasource</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DATASOURCE_FEATURE_COUNT = SOURCE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DimensionImpl <em>Dimension</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DimensionImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getDimension()
   * @generated
   */
  int DIMENSION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Formula</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION__FORMULA = 1;

  /**
   * The number of structural features of the '<em>Dimension</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIMENSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.EndPointImpl <em>End Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.EndPointImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getEndPoint()
   * @generated
   */
  int END_POINT = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_POINT__NAME = SOURCE__NAME;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_POINT__URL = SOURCE_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Parser</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_POINT__PARSER = SOURCE_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>End Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int END_POINT_FEATURE_COUNT = SOURCE_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PostEndPointImpl <em>Post End Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PostEndPointImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getPostEndPoint()
   * @generated
   */
  int POST_END_POINT = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST_END_POINT__NAME = END_POINT__NAME;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST_END_POINT__URL = END_POINT__URL;

  /**
   * The feature id for the '<em><b>Parser</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST_END_POINT__PARSER = END_POINT__PARSER;

  /**
   * The number of structural features of the '<em>Post End Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int POST_END_POINT_FEATURE_COUNT = END_POINT_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GetEndPointImpl <em>Get End Point</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GetEndPointImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getGetEndPoint()
   * @generated
   */
  int GET_END_POINT = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_END_POINT__NAME = END_POINT__NAME;

  /**
   * The feature id for the '<em><b>Url</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_END_POINT__URL = END_POINT__URL;

  /**
   * The feature id for the '<em><b>Parser</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_END_POINT__PARSER = END_POINT__PARSER;

  /**
   * The feature id for the '<em><b>Headers</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_END_POINT__HEADERS = END_POINT_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Get End Point</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GET_END_POINT_FEATURE_COUNT = END_POINT_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.HeaderImpl <em>Header</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.HeaderImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getHeader()
   * @generated
   */
  int HEADER = 11;

  /**
   * The feature id for the '<em><b>Keyword</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__KEYWORD = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER__VALUE = 1;

  /**
   * The number of structural features of the '<em>Header</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HEADER_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SchemaParserImpl <em>Schema Parser</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SchemaParserImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSchemaParser()
   * @generated
   */
  int SCHEMA_PARSER = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_PARSER__NAME = 0;

  /**
   * The feature id for the '<em><b>Schema Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_PARSER__SCHEMA_TYPE = 1;

  /**
   * The feature id for the '<em><b>Selectors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_PARSER__SELECTORS = 2;

  /**
   * The number of structural features of the '<em>Schema Parser</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEMA_PARSER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SelectorImpl
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__NAME = 0;

  /**
   * The feature id for the '<em><b>Steps</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__STEPS = 1;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaType <em>Schema Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaType
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSchemaType()
   * @generated
   */
  int SCHEMA_TYPE = 14;


  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.System <em>System</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.System
   * @generated
   */
  EClass getSystem();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.System#getPages <em>Pages</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pages</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.System#getPages()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Pages();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.System#getSources <em>Sources</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sources</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.System#getSources()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Sources();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.System#getSchemas <em>Schemas</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Schemas</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.System#getSchemas()
   * @see #getSystem()
   * @generated
   */
  EReference getSystem_Schemas();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page <em>Page</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Page</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page
   * @generated
   */
  EClass getPage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page#getName()
   * @see #getPage()
   * @generated
   */
  EAttribute getPage_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page#getTiles <em>Tiles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Tiles</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page#getTiles()
   * @see #getPage()
   * @generated
   */
  EReference getPage_Tiles();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Tile <em>Tile</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Tile</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Tile
   * @generated
   */
  EClass getTile();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Tile#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Tile#getName()
   * @see #getTile()
   * @generated
   */
  EAttribute getTile_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Link <em>Link</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Link</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Link
   * @generated
   */
  EClass getLink();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Link#getPage <em>Page</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Page</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Link#getPage()
   * @see #getLink()
   * @generated
   */
  EReference getLink_Page();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Graph <em>Graph</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Graph</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Graph
   * @generated
   */
  EClass getGraph();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Graph#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Graph#getSource()
   * @see #getGraph()
   * @generated
   */
  EReference getGraph_Source();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Datasource <em>Datasource</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Datasource</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Datasource
   * @generated
   */
  EClass getDatasource();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Datasource#getSource <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Source</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Datasource#getSource()
   * @see #getDatasource()
   * @generated
   */
  EReference getDatasource_Source();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Datasource#getDimensions <em>Dimensions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Dimensions</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Datasource#getDimensions()
   * @see #getDatasource()
   * @generated
   */
  EReference getDatasource_Dimensions();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Dimension <em>Dimension</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Dimension</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Dimension
   * @generated
   */
  EClass getDimension();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Dimension#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Dimension#getName()
   * @see #getDimension()
   * @generated
   */
  EAttribute getDimension_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Dimension#getFormula <em>Formula</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Formula</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Dimension#getFormula()
   * @see #getDimension()
   * @generated
   */
  EReference getDimension_Formula();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Source <em>Source</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Source</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Source
   * @generated
   */
  EClass getSource();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Source#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Source#getName()
   * @see #getSource()
   * @generated
   */
  EAttribute getSource_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.EndPoint <em>End Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>End Point</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.EndPoint
   * @generated
   */
  EClass getEndPoint();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.EndPoint#getUrl <em>Url</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Url</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.EndPoint#getUrl()
   * @see #getEndPoint()
   * @generated
   */
  EAttribute getEndPoint_Url();

  /**
   * Returns the meta object for the reference '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.EndPoint#getParser <em>Parser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Parser</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.EndPoint#getParser()
   * @see #getEndPoint()
   * @generated
   */
  EReference getEndPoint_Parser();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.PostEndPoint <em>Post End Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Post End Point</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.PostEndPoint
   * @generated
   */
  EClass getPostEndPoint();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.GetEndPoint <em>Get End Point</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Get End Point</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.GetEndPoint
   * @generated
   */
  EClass getGetEndPoint();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.GetEndPoint#getHeaders <em>Headers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Headers</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.GetEndPoint#getHeaders()
   * @see #getGetEndPoint()
   * @generated
   */
  EReference getGetEndPoint_Headers();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Header <em>Header</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Header</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Header
   * @generated
   */
  EClass getHeader();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Header#getKeyword <em>Keyword</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Keyword</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Header#getKeyword()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_Keyword();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Header#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Header#getValue()
   * @see #getHeader()
   * @generated
   */
  EAttribute getHeader_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser <em>Schema Parser</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Schema Parser</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser
   * @generated
   */
  EClass getSchemaParser();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser#getName()
   * @see #getSchemaParser()
   * @generated
   */
  EAttribute getSchemaParser_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser#getSchemaType <em>Schema Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Schema Type</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser#getSchemaType()
   * @see #getSchemaParser()
   * @generated
   */
  EAttribute getSchemaParser_SchemaType();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser#getSelectors <em>Selectors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Selectors</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser#getSelectors()
   * @see #getSchemaParser()
   * @generated
   */
  EReference getSchemaParser_Selectors();

  /**
   * Returns the meta object for class '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Selector#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Selector#getName()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Name();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.Selector#getSteps <em>Steps</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Steps</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.Selector#getSteps()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_Steps();

  /**
   * Returns the meta object for enum '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaType <em>Schema Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Schema Type</em>'.
   * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaType
   * @generated
   */
  EEnum getSchemaType();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VizualizerFactory getVizualizerFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SystemImpl <em>System</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SystemImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSystem()
     * @generated
     */
    EClass SYSTEM = eINSTANCE.getSystem();

    /**
     * The meta object literal for the '<em><b>Pages</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__PAGES = eINSTANCE.getSystem_Pages();

    /**
     * The meta object literal for the '<em><b>Sources</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SOURCES = eINSTANCE.getSystem_Sources();

    /**
     * The meta object literal for the '<em><b>Schemas</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM__SCHEMAS = eINSTANCE.getSystem_Schemas();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PageImpl <em>Page</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PageImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getPage()
     * @generated
     */
    EClass PAGE = eINSTANCE.getPage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PAGE__NAME = eINSTANCE.getPage_Name();

    /**
     * The meta object literal for the '<em><b>Tiles</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PAGE__TILES = eINSTANCE.getPage_Tiles();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.TileImpl <em>Tile</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.TileImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getTile()
     * @generated
     */
    EClass TILE = eINSTANCE.getTile();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TILE__NAME = eINSTANCE.getTile_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.LinkImpl <em>Link</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.LinkImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getLink()
     * @generated
     */
    EClass LINK = eINSTANCE.getLink();

    /**
     * The meta object literal for the '<em><b>Page</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LINK__PAGE = eINSTANCE.getLink_Page();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GraphImpl <em>Graph</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GraphImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getGraph()
     * @generated
     */
    EClass GRAPH = eINSTANCE.getGraph();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GRAPH__SOURCE = eINSTANCE.getGraph_Source();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DatasourceImpl <em>Datasource</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DatasourceImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getDatasource()
     * @generated
     */
    EClass DATASOURCE = eINSTANCE.getDatasource();

    /**
     * The meta object literal for the '<em><b>Source</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATASOURCE__SOURCE = eINSTANCE.getDatasource_Source();

    /**
     * The meta object literal for the '<em><b>Dimensions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DATASOURCE__DIMENSIONS = eINSTANCE.getDatasource_Dimensions();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DimensionImpl <em>Dimension</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.DimensionImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getDimension()
     * @generated
     */
    EClass DIMENSION = eINSTANCE.getDimension();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DIMENSION__NAME = eINSTANCE.getDimension_Name();

    /**
     * The meta object literal for the '<em><b>Formula</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIMENSION__FORMULA = eINSTANCE.getDimension_Formula();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SourceImpl <em>Source</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SourceImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSource()
     * @generated
     */
    EClass SOURCE = eINSTANCE.getSource();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOURCE__NAME = eINSTANCE.getSource_Name();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.EndPointImpl <em>End Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.EndPointImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getEndPoint()
     * @generated
     */
    EClass END_POINT = eINSTANCE.getEndPoint();

    /**
     * The meta object literal for the '<em><b>Url</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute END_POINT__URL = eINSTANCE.getEndPoint_Url();

    /**
     * The meta object literal for the '<em><b>Parser</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference END_POINT__PARSER = eINSTANCE.getEndPoint_Parser();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PostEndPointImpl <em>Post End Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.PostEndPointImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getPostEndPoint()
     * @generated
     */
    EClass POST_END_POINT = eINSTANCE.getPostEndPoint();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GetEndPointImpl <em>Get End Point</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.GetEndPointImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getGetEndPoint()
     * @generated
     */
    EClass GET_END_POINT = eINSTANCE.getGetEndPoint();

    /**
     * The meta object literal for the '<em><b>Headers</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GET_END_POINT__HEADERS = eINSTANCE.getGetEndPoint_Headers();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.HeaderImpl <em>Header</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.HeaderImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getHeader()
     * @generated
     */
    EClass HEADER = eINSTANCE.getHeader();

    /**
     * The meta object literal for the '<em><b>Keyword</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__KEYWORD = eINSTANCE.getHeader_Keyword();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HEADER__VALUE = eINSTANCE.getHeader_Value();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SchemaParserImpl <em>Schema Parser</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SchemaParserImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSchemaParser()
     * @generated
     */
    EClass SCHEMA_PARSER = eINSTANCE.getSchemaParser();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEMA_PARSER__NAME = eINSTANCE.getSchemaParser_Name();

    /**
     * The meta object literal for the '<em><b>Schema Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEMA_PARSER__SCHEMA_TYPE = eINSTANCE.getSchemaParser_SchemaType();

    /**
     * The meta object literal for the '<em><b>Selectors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEMA_PARSER__SELECTORS = eINSTANCE.getSchemaParser_Selectors();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.SelectorImpl
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__NAME = eINSTANCE.getSelector_Name();

    /**
     * The meta object literal for the '<em><b>Steps</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__STEPS = eINSTANCE.getSelector_Steps();

    /**
     * The meta object literal for the '{@link org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaType <em>Schema Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaType
     * @see org.xtext.sdu.iotvizualizerlanguage.vizualizer.impl.VizualizerPackageImpl#getSchemaType()
     * @generated
     */
    EEnum SCHEMA_TYPE = eINSTANCE.getSchemaType();

  }

} //VizualizerPackage
