/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FormularAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/sdu/formularzlanguage/parser/antlr/internal/InternalFormular.tokens");
	}
}
