/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.sdu.iotvizualizerlanguage.ui.internal.IotvizualizerlanguageActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VizualizerExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return IotvizualizerlanguageActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return IotvizualizerlanguageActivator.getInstance().getInjector(IotvizualizerlanguageActivator.ORG_XTEXT_SDU_IOTVIZUALIZERLANGUAGE_VIZUALIZER);
	}
	
}
