/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.tests

import com.google.inject.Inject
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.xtext.sdu.formularzlanguage.formular.Expression

@RunWith(XtextRunner)
@InjectWith(FormularInjectorProvider)
class FormularParsingTest{

	@Inject
	ParseHelper<Expression> parseHelper;

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}

}
