/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage


class FormularStandaloneSetup extends FormularStandaloneSetupGenerated {

	def static void doSetup() {
		new FormularStandaloneSetup().createInjectorAndDoEMFRegistration()
	}

}
