/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.sdu.formularzlanguage.ui.AbstractFormularUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class FormularUiModule extends AbstractFormularUiModule {
  public FormularUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
