/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFormularScopeProvider extends DelegatingScopeProvider {
}
