/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.sdu.formularzlanguage.formular.Expression;
import org.xtext.sdu.formularzlanguage.formular.Factor;
import org.xtext.sdu.formularzlanguage.formular.Formula;
import org.xtext.sdu.formularzlanguage.formular.FormularPackage;
import org.xtext.sdu.formularzlanguage.formular.Variable;
import org.xtext.sdu.formularzlanguage.serializer.FormularSemanticSequencer;
import org.xtext.sdu.iotvizualizerlanguage.services.VizualizerGrammarAccess;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Api;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Graph;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Link;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.VizualizerPackage;

@SuppressWarnings("all")
public class VizualizerSemanticSequencer extends FormularSemanticSequencer {

	@Inject
	private VizualizerGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == FormularPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case FormularPackage.EXPRESSION:
				sequence_Expression(context, (Expression) semanticObject); 
				return; 
			case FormularPackage.FACTOR:
				sequence_Factor(context, (Factor) semanticObject); 
				return; 
			case FormularPackage.FORMULA:
				sequence_Formula(context, (Formula) semanticObject); 
				return; 
			case FormularPackage.MATH:
				sequence_Math(context, (org.xtext.sdu.formularzlanguage.formular.Math) semanticObject); 
				return; 
			case FormularPackage.NUMBER:
				sequence_Number(context, (org.xtext.sdu.formularzlanguage.formular.Number) semanticObject); 
				return; 
			case FormularPackage.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			}
		else if (epackage == VizualizerPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case VizualizerPackage.API:
				sequence_Api(context, (Api) semanticObject); 
				return; 
			case VizualizerPackage.GRAPH:
				sequence_Graph(context, (Graph) semanticObject); 
				return; 
			case VizualizerPackage.LINK:
				sequence_Link(context, (Link) semanticObject); 
				return; 
			case VizualizerPackage.PAGE:
				sequence_Page(context, (Page) semanticObject); 
				return; 
			case VizualizerPackage.SYSTEM:
				sequence_System(context, (org.xtext.sdu.iotvizualizerlanguage.vizualizer.System) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Api returns Api
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Api(ISerializationContext context, Api semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.API__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.API__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getApiAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Tile returns Graph
	 *     Graph returns Graph
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_Graph(ISerializationContext context, Graph semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.TILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.TILE__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getGraphAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Tile returns Link
	 *     Link returns Link
	 *
	 * Constraint:
	 *     (name=ID page=[Page|ID])
	 */
	protected void sequence_Link(ISerializationContext context, Link semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.TILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.TILE__NAME));
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.LINK__PAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.LINK__PAGE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLinkAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getLinkAccess().getPagePageIDTerminalRuleCall_3_0_1(), semanticObject.getPage());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Page returns Page
	 *
	 * Constraint:
	 *     (name=ID tiles+=Tile*)
	 */
	protected void sequence_Page(ISerializationContext context, Page semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     System returns System
	 *
	 * Constraint:
	 *     ((pages+=Page+ apis+=Api+) | apis+=Api+)?
	 */
	protected void sequence_System(ISerializationContext context, org.xtext.sdu.iotvizualizerlanguage.vizualizer.System semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
