/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.sdu.formularzlanguage.formular.Expression;
import org.xtext.sdu.formularzlanguage.formular.Factor;
import org.xtext.sdu.formularzlanguage.formular.Formula;
import org.xtext.sdu.formularzlanguage.formular.FormularPackage;
import org.xtext.sdu.formularzlanguage.formular.Variable;
import org.xtext.sdu.formularzlanguage.serializer.FormularSemanticSequencer;
import org.xtext.sdu.iotvizualizerlanguage.services.VizualizerGrammarAccess;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Datasource;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Dimension;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.DimensionSelector;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.GetEndPoint;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Graph;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Header;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Link;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.NoQuotesString;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Page;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.PostEndPoint;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.SchemaParser;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.Selector;
import org.xtext.sdu.iotvizualizerlanguage.vizualizer.VizualizerPackage;

@SuppressWarnings("all")
public class VizualizerSemanticSequencer extends FormularSemanticSequencer {

	@Inject
	private VizualizerGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == FormularPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case FormularPackage.EXPRESSION:
				sequence_Expression(context, (Expression) semanticObject); 
				return; 
			case FormularPackage.FACTOR:
				sequence_Factor(context, (Factor) semanticObject); 
				return; 
			case FormularPackage.FORMULA:
				sequence_Formula(context, (Formula) semanticObject); 
				return; 
			case FormularPackage.NUMBER:
				sequence_Number(context, (org.xtext.sdu.formularzlanguage.formular.Number) semanticObject); 
				return; 
			case FormularPackage.VARIABLE:
				sequence_Variable(context, (Variable) semanticObject); 
				return; 
			}
		else if (epackage == VizualizerPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case VizualizerPackage.DATASOURCE:
				sequence_Datasource(context, (Datasource) semanticObject); 
				return; 
			case VizualizerPackage.DIMENSION:
				sequence_Dimension(context, (Dimension) semanticObject); 
				return; 
			case VizualizerPackage.DIMENSION_SELECTOR:
				sequence_DimensionSelector(context, (DimensionSelector) semanticObject); 
				return; 
			case VizualizerPackage.GET_END_POINT:
				sequence_GetEndPoint(context, (GetEndPoint) semanticObject); 
				return; 
			case VizualizerPackage.GRAPH:
				sequence_Graph(context, (Graph) semanticObject); 
				return; 
			case VizualizerPackage.HEADER:
				sequence_Header(context, (Header) semanticObject); 
				return; 
			case VizualizerPackage.LINK:
				sequence_Link(context, (Link) semanticObject); 
				return; 
			case VizualizerPackage.NO_QUOTES_STRING:
				sequence_NoQuotesString(context, (NoQuotesString) semanticObject); 
				return; 
			case VizualizerPackage.PAGE:
				sequence_Page(context, (Page) semanticObject); 
				return; 
			case VizualizerPackage.POST_END_POINT:
				sequence_PostEndPoint(context, (PostEndPoint) semanticObject); 
				return; 
			case VizualizerPackage.SCHEMA_PARSER:
				sequence_SchemaParser(context, (SchemaParser) semanticObject); 
				return; 
			case VizualizerPackage.SELECTOR:
				sequence_Selector(context, (Selector) semanticObject); 
				return; 
			case VizualizerPackage.SYSTEM:
				sequence_System(context, (org.xtext.sdu.iotvizualizerlanguage.vizualizer.System) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Datasource returns Datasource
	 *     Source returns Datasource
	 *
	 * Constraint:
	 *     (name=ID dimensions+=Dimension dimensions+=Dimension*)
	 */
	protected void sequence_Datasource(ISerializationContext context, Datasource semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     DimensionSelector returns DimensionSelector
	 *
	 * Constraint:
	 *     (source=[Source|ID] selectVar=NoQuotesString name=ID)
	 */
	protected void sequence_DimensionSelector(ISerializationContext context, DimensionSelector semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.DIMENSION_SELECTOR__SOURCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.DIMENSION_SELECTOR__SOURCE));
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.DIMENSION_SELECTOR__SELECT_VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.DIMENSION_SELECTOR__SELECT_VAR));
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.DIMENSION_SELECTOR__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.DIMENSION_SELECTOR__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDimensionSelectorAccess().getSourceSourceIDTerminalRuleCall_1_0_1(), semanticObject.getSource());
		feeder.accept(grammarAccess.getDimensionSelectorAccess().getSelectVarNoQuotesStringParserRuleCall_3_0(), semanticObject.getSelectVar());
		feeder.accept(grammarAccess.getDimensionSelectorAccess().getNameIDTerminalRuleCall_6_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Dimension returns Dimension
	 *
	 * Constraint:
	 *     (name=Formula sourceSelectors+=DimensionSelector sourceSelectors+=DimensionSelector*)
	 */
	protected void sequence_Dimension(ISerializationContext context, Dimension semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Source returns GetEndPoint
	 *     EndPoint returns GetEndPoint
	 *     GetEndPoint returns GetEndPoint
	 *
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         url=STRING 
	 *         json=STRING? 
	 *         headers+=Header 
	 *         headers+=Header* 
	 *         parser=[SchemaParser|ID]
	 *     )
	 */
	protected void sequence_GetEndPoint(ISerializationContext context, GetEndPoint semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Tile returns Graph
	 *     Graph returns Graph
	 *
	 * Constraint:
	 *     (name=ID source=[Datasource|ID] lael=STRING?)
	 */
	protected void sequence_Graph(ISerializationContext context, Graph semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Header returns Header
	 *
	 * Constraint:
	 *     (keyword=STRING value=STRING)
	 */
	protected void sequence_Header(ISerializationContext context, Header semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.HEADER__KEYWORD) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.HEADER__KEYWORD));
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.HEADER__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.HEADER__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getHeaderAccess().getKeywordSTRINGTerminalRuleCall_0_0(), semanticObject.getKeyword());
		feeder.accept(grammarAccess.getHeaderAccess().getValueSTRINGTerminalRuleCall_2_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Tile returns Link
	 *     Link returns Link
	 *
	 * Constraint:
	 *     (name=ID page=[Page|ID])
	 */
	protected void sequence_Link(ISerializationContext context, Link semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.TILE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.TILE__NAME));
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.LINK__PAGE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.LINK__PAGE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getLinkAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getLinkAccess().getPagePageIDTerminalRuleCall_3_0_1(), semanticObject.getPage());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     NoQuotesString returns NoQuotesString
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_NoQuotesString(ISerializationContext context, NoQuotesString semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.NO_QUOTES_STRING__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.NO_QUOTES_STRING__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNoQuotesStringAccess().getNameIDTerminalRuleCall_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Page returns Page
	 *
	 * Constraint:
	 *     (name=ID tiles+=Tile*)
	 */
	protected void sequence_Page(ISerializationContext context, Page semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Source returns PostEndPoint
	 *     EndPoint returns PostEndPoint
	 *     PostEndPoint returns PostEndPoint
	 *
	 * Constraint:
	 *     (name=ID url=STRING parser=[SchemaParser|ID])
	 */
	protected void sequence_PostEndPoint(ISerializationContext context, PostEndPoint semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.SOURCE__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.SOURCE__NAME));
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.END_POINT__URL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.END_POINT__URL));
			if (transientValues.isValueTransient(semanticObject, VizualizerPackage.Literals.END_POINT__PARSER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, VizualizerPackage.Literals.END_POINT__PARSER));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getPostEndPointAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getPostEndPointAccess().getUrlSTRINGTerminalRuleCall_4_0(), semanticObject.getUrl());
		feeder.accept(grammarAccess.getPostEndPointAccess().getParserSchemaParserIDTerminalRuleCall_6_0_1(), semanticObject.getParser());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     SchemaParser returns SchemaParser
	 *
	 * Constraint:
	 *     (name=ID schemaType=SchemaType selectors+=Selector+)
	 */
	protected void sequence_SchemaParser(ISerializationContext context, SchemaParser semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Selector returns Selector
	 *
	 * Constraint:
	 *     (name=ID steps+=STRING steps+=STRING+)
	 */
	protected void sequence_Selector(ISerializationContext context, Selector semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     System returns System
	 *
	 * Constraint:
	 *     (pages+=Page | sources+=Source | schemas+=SchemaParser)+
	 */
	protected void sequence_System(ISerializationContext context, org.xtext.sdu.iotvizualizerlanguage.vizualizer.System semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
