/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.sdu.iotvizualizerlanguage.parser.antlr.internal.InternalVizualizerParser;
import org.xtext.sdu.iotvizualizerlanguage.services.VizualizerGrammarAccess;

public class VizualizerParser extends AbstractAntlrParser {

	@Inject
	private VizualizerGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalVizualizerParser createParser(XtextTokenStream stream) {
		return new InternalVizualizerParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}

	public VizualizerGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(VizualizerGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
