/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.junit4.IInjectorProvider;
import org.xtext.sdu.iotvizualizerlanguage.ui.internal.IotvizualizerlanguageActivator;

public class VizualizerUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return IotvizualizerlanguageActivator.getInstance().getInjector("org.xtext.sdu.iotvizualizerlanguage.Vizualizer");
	}

}
