# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 15:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdatamodel',
            name='content',
            field=models.CharField(default=datetime.datetime(2016, 5, 18, 15, 38, 9, 990701, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdatamodel',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 18, 15, 38, 32, 548698, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testdatamodel',
            name='name',
            field=models.CharField(default='deafault', max_length=200),
            preserve_default=False,
        ),
    ]
