/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.formular.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.sdu.formularzlanguage.formular.Expreession;
import org.xtext.sdu.formularzlanguage.formular.FormularPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Expreession</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * </p>
 *
 * @generated
 */
public class ExpreessionImpl extends ExpressionImpl implements Expreession
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExpreessionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return FormularPackage.Literals.EXPREESSION;
  }

} //ExpreessionImpl
