/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.ui.quickfix;

import org.xtext.sdu.formularzlanguage.ui.quickfix.FormularQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class VizualizerQuickfixProvider extends FormularQuickfixProvider {
}
