/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.validation;

import org.xtext.sdu.formularzlanguage.validation.AbstractFormularValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class FormularValidator extends AbstractFormularValidator {
}
