/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage.validation;

import org.xtext.sdu.iotvizualizerlanguage.validation.AbstractVizualizerValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VizualizerValidator extends AbstractVizualizerValidator {
}
