/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.iotvizualizerlanguage;

import org.xtext.sdu.iotvizualizerlanguage.VizualizerStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class VizualizerStandaloneSetup extends VizualizerStandaloneSetupGenerated {
  public static void doSetup() {
    VizualizerStandaloneSetup _vizualizerStandaloneSetup = new VizualizerStandaloneSetup();
    _vizualizerStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
