/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.formular;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.sdu.formularzlanguage.formular.FormularPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
} // Expression
