/**
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage;

import org.xtext.sdu.formularzlanguage.AbstractFormularRuntimeModule;

@SuppressWarnings("all")
public class FormularRuntimeModule extends AbstractFormularRuntimeModule {
}
