/*
 * generated by Xtext 2.9.2
 */
package org.xtext.sdu.formularzlanguage.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractFormularValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(org.xtext.sdu.formularzlanguage.formular.FormularPackage.eINSTANCE);
		return result;
	}
	
}
